### ISSUE TITLE
JwtStrategy Error

### ISSUE THREAD

**Issue by genxhero** [genxhero/wayfarer#2]
I am not sure which branch is the cause of this but i am at present unable to test my components on account of a server error.  I was able to test my code at home before pulling this morning.

[0] TypeError: JwtStrategy requires a secret or key
[0]     at new JwtStrategy (/Users/aarongoddard/Documents/Coding/wayfarer/node_modules/passport-jwt/lib/strategy.js:45:15)
[0]     at module.exports.passport (/Users/aarongoddard/Documents/Coding/wayfarer/config/passport.js:12:16)
[0]     at Object.<anonymous> (/Users/aarongoddard/Documents/Coding/wayfarer/routes/api/users.js:8:33)
[0]     at Module._compile (internal/modules/cjs/loader.js:689:30)
[0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
[0]     at Module.load (internal/modules/cjs/loader.js:599:32)
[0]     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
[0]     at Module.require (internal/modules/cjs/loader.js:637:17)
[0]     at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/aarongoddard/Documents/Coding/wayfarer/app.js:6:15)
[0]     at Module._compile (internal/modules/cjs/loader.js:689:30)
[0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
[0]     at Module.load (internal/modules/cjs/loader.js:599:32)
[0]     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
[0] [nodemon] app crashed - waiting for file changes before starting...

**Comment by uncertainkitten** [comment]
Seems to be an issue with reconciling npm packages - I think once the master package.json and package.json-lock sync with mine, we'll be ok.
